name: dl-hosttools

on:
# push:
#   branches: [ master ]
#   paths:
#     - '.github/workflows/dl-hosttools.yml'
#     - 'tools/dl-hosttools'
#     - 'tools/make/'
  workflow_dispatch:

jobs:
  build:
    container:
#     image: ubuntu:18.04
      image: freetzng/dl-packs
    runs-on: ubuntu-latest

    steps:

#     - name: update
#       run: apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade
#
#     - name: install
#       run: |
#         DEBIAN_FRONTEND=noninteractive apt-get -y install \
#           locales \
#           pv cpio rsync kmod execstack imagemagick inkscape graphicsmagick subversion git bc unar wget sudo gcc g++ binutils autoconf automake \
#           autopoint libtool-bin make bzip2 libncurses5-dev libreadline-dev zlib1g-dev flex bison patch texinfo tofrodos gettext pkg-config ecj \
#           fastjar perl libstring-crc32-perl ruby ruby1.9 gawk python libusb-dev unzip intltool libacl1-dev libcap-dev libc6-dev-i386 lib32ncurses5-dev \
#           gcc-multilib bsdmainutils lib32stdc++6 libglib2.0-dev ccache cmake lib32z1-dev libsqlite3-dev sqlite3 libzstd-dev netcat curl openssl \
#           build-essential
#
#     - name: locale
#       run: locale-gen en_US.utf8 && locale-gen de_DE.UTF-8 && update-locale

      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          umask 0022
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git clone https://github-actions:$GITHUB_TOKEN@${GITHUB_SERVER_URL##*/}/$GITHUB_REPOSITORY.git $GITHUB_WORKSPACE --branch $GITHUB_REF_NAME

      - name: cache
        uses: actions/cache@v3.0.2
        with:
          path: |
            dl/*
            !dl/tools-*.tar.xz
          key: ${{ github.workflow }}-20220526

      - name: version
        id: version
        run: |
          export VERSION="r$(tools/freetz_revision short)"
          [ -n "$VERSION" ] && echo "::set-output name=version::$VERSION" || exit 1
          echo "################################################################" && bash -c "echo VERSION=$VERSION"

      - name: generate
        env:
          ACTIONS_VERSION: ${{ steps.version.outputs.version }}
        run: |
          mkdir -p dl/ 2>/dev/null || true
          useradd freetz -s $(which bash) -d $(pwd) -M && chown freetz . -R
          su freetz -c "umask 0022 && tools/dl-hosttools $ACTIONS_VERSION && rm -f tools-$ACTIONS_VERSION.*"

      - name: cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git tag -d dl-hosttools && git push --delete origin dl-hosttools || true

      - name: release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: dl-hosttools
          name: dl-hosttools
          body: These files are internally used!
          prerelease: true
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: false
          artifactErrorsFailBuild: true
          artifacts: "dl/tools-${{ steps.version.outputs.version }}.tar.xz"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false

      - name: bump
        env:
          ACTIONS_VERSION: ${{ steps.version.outputs.version }}
        run: |
          SHA256="$(sha256sum dl/tools-$ACTIONS_VERSION.tar.xz)"
          sed -r "s/^(\\$\(call TOOLS_INIT,).*/\1 ${ACTIONS_VERSION})/"                                               -i tools/make/tools-host/tools-host.mk
          sed -r "s/^(\\$\(PKG\)_HASH:)=.*/\1=${SHA256%% *}/"                                                         -i tools/make/tools-host/tools-host.mk
          sed -r "s,^(\\$\(PKG\)_SITE:)=.*,\1=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/dl-hosttools,"  -i tools/make/tools-host/tools-host.mk

#     - name: commit
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         git config --global --add safe.directory $GITHUB_WORKSPACE
#         git pull
#         git add .
#         git status
#         git config --local user.name github-actions
#         git config --local user.email github-actions@github.com
#         git diff --cached --quiet && exit 0 || git commit -m "dl-hosttools: automatic update"
#         git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
#         git push origin $GITHUB_REF_NAME


