name: generate_img

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/generate_img.yml'
      - 'config/generate_img.sh'
      - 'config/mod/download.in'
  workflow_dispatch:

jobs:
  build:
    container:
#     image: ubuntu:18.04
      image: freetzng/dl-packs
    runs-on: ubuntu-latest

    steps:

#     - name: update
#       run: apt-get -y update && apt-get -y upgrade && apt-get -y dist-upgrade
#
#     - name: install
#       run: |
#         DEBIAN_FRONTEND=noninteractive apt-get -y install \
#           locales bash \
#           cpio rsync kmod execstack sqlite3 libsqlite3-dev libzstd-dev cmake lib32z1-dev unar subversion git bc wget sudo gcc g++ binutils autoconf automake autopoint \
#           libtool-bin make bzip2 libncurses5-dev libreadline-dev zlib1g-dev flex bison patch texinfo tofrodos gettext pkg-config ecj fastjar perl libstring-crc32-perl \
#           ruby gawk python libusb-dev unzip intltool libacl1-dev libcap-dev libc6-dev-i386 lib32ncurses5-dev gcc-multilib lib32stdc++6 libglib2.0-dev
#
#     - name: locale
#       run: locale-gen en_US.utf8 && locale-gen de_DE.UTF-8 && update-locale

      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          umask 0022
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git clone https://github-actions:$GITHUB_TOKEN@${GITHUB_SERVER_URL##*/}/$GITHUB_REPOSITORY.git $GITHUB_WORKSPACE --branch $GITHUB_REF_NAME

      - name: tools
        run: |
          echo 'FREETZ_USER_LEVEL_APTGURU=y\nFREETZ_HOSTTOOLS_DOWNLOAD=y\nFREETZ_DL_SITE_USER="https://raw.githubusercontent.com/Freetz-NG/dl-mirror/master"' > .config
          mkdir -p dl/ 2>/dev/null || true
          useradd freetz -s $(which bash) -d $(pwd) -M && chown freetz . -R
          su freetz -c "umask 0022 && make olddefconfig && make tools"

      - name: generate
        env:
          ACTIONS_FWDLURL: ${{ secrets.ACTIONS_FWDLURL }}
        run: |
          export LANG=en_US.utf8
          mkdir -p ~/.freetz-props/ 2>/dev/null || true
          mkdir -p ~/.freetz-dl/fw/ 2>/dev/null || true
          FREETZ_ENABLEG=true config/generate_img.sh

      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git pull
          git add .
          git status
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git diff --cached --quiet && exit 0 || git commit -m "img: automatic update"
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git push origin $GITHUB_REF_NAME


